package com.velocityx.wallet_service.enums;

public enum WalletEventType {
    CREDIT_REQUESTED,
    CREDIT_COMPLETED,
    CREDIT_FAILED,
    DEBIT_REQUESTED,
    DEBIT_COMPLETED,
    DEBIT_FAILED,
    HOLD_REQUESTED,
    HOLD_COMPLETED,
    HOLD_FAILED,
    CAPTURE_REQUESTED,
    CAPTURE_COMPLETED,
    CAPTURE_FAILED,
    RELEASE_REQUESTED,
    RELEASE_COMPLETED,
    TRANSFER_REQUESTED,
    TRANSFER_COMPLETED,
    TRANSFER_FAILED,
    REFUND_REQUESTED,
    REFUND_COMPLETED
}
